[package]
name = "wget_filter"
version = "0.1.0"
authors = ["nmaeda <nmaeda@keepdata.asia>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
